// ─── App domain types ────────────────────────────────────────────────────────

export type Lang = "mr" | "hi" | "en";

export type ServiceCategory = "gov" | "farm" | "online";
export type PaymentProvider = "none" | "stripe" | "razorpay" | "manual_qr";
export type FormFieldType = "text" | "number" | "date" | "textarea" | "select" | "file" | "checkbox" | "radio";
export type UserRole = "admin" | "citizen";
export type UserStatus = "active" | "suspended";
export type ThemeMode = "light" | "dark" | "system";
export type ThemeAppearance = "light" | "dark";
export type ThemeTokenMap = Record<string, string>;

export interface ServiceItem {
  id: string;
  category: ServiceCategory;
  title: { mr: string; hi: string; en: string };
  desc: { mr: string; hi: string; en: string };
  long?: { mr: string; hi: string; en: string };
  docs: Array<{ mr: string; hi: string; en: string }>;
  fee?: { mr: string; hi: string; en: string };
  time?: { mr: string; hi: string; en: string };
}

export interface ContactFormData {
  name: string;
  email: string;
  phone: string;
  message: string;
}

// ─── Service application / lifecycle types ───────────────────────────────────

/**
 * Full lifecycle of a service application:
 *   submitted → received → processing → ready → completed
 */
export type ApplicationStatus =
  | "submitted"
  | "received"
  | "processing"
  | "ready"
  | "completed";

export interface ServiceApplication {
  id: string;
  /** Public tracking code, e.g. DYW-1024 */
  code: string;
  user_id?: string;
  user_email?: string;
  user_name: string;
  phone: string;
  service_id: string;
  service_name: string;
  status: ApplicationStatus;
  admin_notes?: string;
  submitted_payload?: Record<string, string>;
  submitted_documents?: SubmittedDocument[];
  payment_status: "pending" | "verified" | "rejected" | "paid";
  payment_provider: PaymentProvider;
  payment_reference?: string;
  transaction_id?: string;
  amount: number;
  created_at: string;
  updated_at: string;
}

export interface ApplyFormData {
  user_name: string;
  phone: string;
  service_id: string;
  service_name: string;
  form_payload?: Record<string, string>;
  submitted_documents?: SubmittedDocument[];
  payment_status?: "pending" | "verified" | "rejected" | "paid";
  payment_provider?: PaymentProvider;
  payment_reference?: string;
  transaction_id?: string;
  amount?: number;
}

export interface SubmittedDocument {
  name: string;
  kind?: "required_document" | "dynamic_field_file" | "payment_proof";
  path?: string;
  url?: string;
  mime_type?: string;
  size?: number;
  uploaded_at?: string;
}

export interface UserProfile {
  id: string;
  email: string;
  full_name: string;
  phone?: string;
  role: UserRole;
  status: UserStatus;
  suspended_at?: string;
  created_at: string;
  updated_at: string;
}

export interface ServiceFormField {
  id: string;
  key: string;
  label: string;
  type: FormFieldType;
  options?: string[];
  required: boolean;
}

export interface ManagedService {
  id: string;
  category: ServiceCategory;
  title: string;
  description: string;
  details?: string;
  image_url?: string;
  required_documents: string[];
  fee_amount: number;
  fee_note?: string;
  payment_provider: PaymentProvider;
  payment_qr_image_url?: string;
  form_schema: ServiceFormField[];
  active: boolean;
}

// ─── Supabase database types (scaffold — fill in once backend is live) ────────
// These mirror the Supabase table schema generated by `supabase gen types`.
//
// To activate: run the following SQL in your Supabase project:
//
// create table public.service_applications (
//   id          uuid primary key default gen_random_uuid(),
//   code        text unique not null,
//   user_id     uuid references auth.users(id),
//   user_email  text,
//   user_name   text not null,
//   phone       text not null,
//   service_id  text not null,
//   service_name text not null,
//   status      text not null default 'submitted',
//   admin_notes text,
//   created_at  timestamptz default now(),
//   updated_at  timestamptz default now()
// );
// alter table public.service_applications enable row level security;
// -- Users can read/insert their own rows; admins can read/update all.

export interface Database {
  public: {
    Tables: {
      service_applications: {
        Row: {
          id: string;
          code: string;
          user_id: string | null;
          user_email: string | null;
          user_name: string;
          phone: string;
          service_id: string;
          service_name: string;
          status: ApplicationStatus;
          admin_notes: string | null;
          submitted_payload: Record<string, string> | null;
          submitted_documents: SubmittedDocument[] | null;
          payment_status: "pending" | "verified" | "rejected" | "paid";
          payment_provider: PaymentProvider | null;
          payment_reference: string | null;
          transaction_id: string | null;
          amount: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_name: string;
          phone: string;
          service_id: string;
          service_name: string;
          status?: ApplicationStatus;
          admin_notes?: string | null;
          submitted_payload?: Record<string, string> | null;
          submitted_documents?: SubmittedDocument[] | null;
          payment_status?: "pending" | "verified" | "rejected" | "paid";
          payment_provider?: PaymentProvider | null;
          payment_reference?: string | null;
          transaction_id?: string | null;
          amount?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          code?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_name?: string;
          phone?: string;
          service_id?: string;
          service_name?: string;
          status?: ApplicationStatus;
          admin_notes?: string | null;
          submitted_payload?: Record<string, string> | null;
          submitted_documents?: SubmittedDocument[] | null;
          payment_status?: "pending" | "verified" | "rejected" | "paid";
          payment_provider?: PaymentProvider | null;
          payment_reference?: string | null;
          transaction_id?: string | null;
          amount?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          category: ServiceCategory;
          title: string;
          description: string;
          details: string | null;
          image_url: string | null;
          required_documents: string[];
          fee_amount: number;
          fee_note: string | null;
          payment_provider: PaymentProvider;
          payment_qr_image_url: string | null;
          form_schema: ServiceFormField[];
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          category: ServiceCategory;
          title: string;
          description: string;
          details?: string | null;
          image_url?: string | null;
          required_documents?: string[];
          fee_amount?: number;
          fee_note?: string | null;
          payment_provider?: PaymentProvider;
          payment_qr_image_url?: string | null;
          form_schema?: ServiceFormField[];
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          category?: ServiceCategory;
          title?: string;
          description?: string;
          details?: string | null;
          image_url?: string | null;
          required_documents?: string[];
          fee_amount?: number;
          fee_note?: string | null;
          payment_provider?: PaymentProvider;
          payment_qr_image_url?: string | null;
          form_schema?: ServiceFormField[];
          active?: boolean;
        };
      };
      contact_requests: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          message: string;
          status: "new" | "read" | "replied" | "in_progress" | "resolved";
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone: string;
          message: string;
          status?: "new" | "read" | "replied" | "in_progress" | "resolved";
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          email?: string;
          phone?: string;
          message?: string;
          status?: "new" | "read" | "replied" | "in_progress" | "resolved";
          source?: string;
          updated_at?: string;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          role: UserRole;
          status: UserStatus;
          suspended_at: string | null;
          theme_mode: ThemeMode;
          preferred_theme_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          phone?: string | null;
          role?: UserRole;
          status?: UserStatus;
          suspended_at?: string | null;
          theme_mode?: ThemeMode;
          preferred_theme_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          email?: string;
          full_name?: string;
          phone?: string | null;
          role?: UserRole;
          status?: UserStatus;
          suspended_at?: string | null;
          theme_mode?: ThemeMode;
          preferred_theme_id?: string | null;
          updated_at?: string;
        };
      };
      app_themes: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          appearance: ThemeAppearance;
          tokens: ThemeTokenMap;
          active: boolean;
          built_in: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          description?: string | null;
          appearance?: ThemeAppearance;
          tokens?: ThemeTokenMap;
          active?: boolean;
          built_in?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          appearance?: ThemeAppearance;
          tokens?: ThemeTokenMap;
          active?: boolean;
          built_in?: boolean;
          updated_at?: string;
        };
      };
      app_theme_settings: {
        Row: {
          id: number;
          default_theme_id: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          default_theme_id: string;
          updated_at?: string;
        };
        Update: {
          default_theme_id?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
