// ─── App domain types ────────────────────────────────────────────────────────

export type Lang = "mr" | "hi" | "en";

export type ServiceCategory = "gov" | "farm" | "online";

export interface ServiceItem {
  id: string;
  category: ServiceCategory;
  title: { mr: string; hi: string; en: string };
  desc: { mr: string; hi: string; en: string };
  long?: { mr: string; hi: string; en: string };
  docs: Array<{ mr: string; hi: string; en: string }>;
  fee?: { mr: string; hi: string; en: string };
  time?: { mr: string; hi: string; en: string };
}

export interface ContactFormData {
  name: string;
  phone: string;
  message: string;
}

// ─── Service application / lifecycle types ───────────────────────────────────

/**
 * Full lifecycle of a service application:
 *   submitted → received → processing → ready → completed
 */
export type ApplicationStatus =
  | "submitted"
  | "received"
  | "processing"
  | "ready"
  | "completed";

export interface ServiceApplication {
  id: string;
  /** Public tracking code, e.g. DYW-1024 */
  code: string;
  user_id?: string;
  user_email?: string;
  user_name: string;
  phone: string;
  service_id: string;
  service_name: string;
  status: ApplicationStatus;
  admin_notes?: string;
  created_at: string;
  updated_at: string;
}

export interface ApplyFormData {
  user_name: string;
  phone: string;
  service_id: string;
  service_name: string;
}

// ─── Supabase database types (scaffold — fill in once backend is live) ────────
// These mirror the Supabase table schema generated by `supabase gen types`.
//
// To activate: run the following SQL in your Supabase project:
//
// create table public.service_applications (
//   id          uuid primary key default gen_random_uuid(),
//   code        text unique not null,
//   user_id     uuid references auth.users(id),
//   user_email  text,
//   user_name   text not null,
//   phone       text not null,
//   service_id  text not null,
//   service_name text not null,
//   status      text not null default 'submitted',
//   admin_notes text,
//   created_at  timestamptz default now(),
//   updated_at  timestamptz default now()
// );
// alter table public.service_applications enable row level security;
// -- Users can read/insert their own rows; admins can read/update all.

export interface Database {
  public: {
    Tables: {
      service_applications: {
        Row: {
          id: string;
          code: string;
          user_id: string | null;
          user_email: string | null;
          user_name: string;
          phone: string;
          service_id: string;
          service_name: string;
          status: ApplicationStatus;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_name: string;
          phone: string;
          service_id: string;
          service_name: string;
          status?: ApplicationStatus;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          code?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_name?: string;
          phone?: string;
          service_id?: string;
          service_name?: string;
          status?: ApplicationStatus;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
